services:
  db:
    container_name: cricket-spring-boot
    image: postgres:latest
    environment:
      POSTGRES_USER: playercode
      POSTGRES_PASSWORD: password
      PGDATA: /data/postgres
    volumes:
      - db:/data/postgres
    ports:
      - "5555:5432"
    networks:
      - db
    restart: unless-stopped

networks:
  db:
    driver: bridge
volumes:
  db: